
### package imports
##########################################################
import os
import socket
import sys
from pathlib import Path

import numpy as np
import pandas as pd

import datetime




### setup
##########################################################

# load dataset
lsms_pd = pd.read_csv("../AfricanCropCalendar.csv")


### correct errors in mixed string-integer variables (trailing .0; whitespaces; etc.)
#####

# clean identifier variables
id_vars = ["hhID", "fieldID", "plotID"]

for var in id_vars:

    lsms_pd[var] = (
        lsms_pd[var]

        # preserve missing values properly
        .astype("string")

        # remove leading/trailing whitespace
        .str.strip()

        # remove trailing ".0" introduced by Excel/R numeric conversion
        .str.replace(r"\.0$", "", regex=True)
    )





### add harmonised crop name
##########################################################

# list all cropnames in dataset: start
crop_obs_start_lst = sorted(lsms_pd["crop"].unique().tolist())

# list of core crops
crop_target_lst = [
 'acacia',
 'agbono (oro seed)',
 'albizia lebbeck',
 'amaranth',
 'apple',
 'avocado',
 'bambara bean',
 'bamboo',
 'banana',
 'banana beer',
 'barley',
 'baobab',
 'bean',
 'cowpea',
 'beans/cowpea',
 'beet',
 'bell pepper',
 'bitter kola',
 'black cumin',
 'black pepper',
 'blackberry',
 'blue gum',
 'cabbage',
 'cactus',
 'calabash',
 'cardamon',
 'carrot',
 'cashew nut',
 'cassava',
 'castor bean',
 'cauliflower',
 'celery',
 'chat',
 'chickpea',
 'chilli pepper',
 'cinnamon',
 'citron',
 'clover',
 'cocoa', 
 'coconut',
 'cocoyam',
 'cofee + banana',
 'coffee', 
 'coffee, avocado, bluegum, banana peaches papaya tangerine',
 'coriander',
 'cotton',
 'cotton seed',
 'cowpea',
 'cucumber',
 'custard apple', 
 'dates',
 'plantain',
 'dwelling tree',
 'eggplant',
 'enset',
 'fennel',
 'fenugreek',
 'field pea',
 'finger millet',
 'fodder cowpea',
 'fonio',
 'fruit',
 'fuel wood tree',
 'garden egg',
 'garlic',
 'gesho',
 'ginger',
 'gliricidia',
 'glue tree',
 'granadilla',
 'grape fruit',
 'grapes',
 'green bean',
 'green pepper',
 'green sorrel',
 'green vegetable',
 'ground bean',
 'groundnut',
 'guava',
 'haricot bean',
 'horse bean',
 'hybrid maize _cassava',
 'jackfruit',
 'jambula',
 'kachere tree',
 'kadale trees',
 'kalama trees',
 'kale',
 'kantchidwi trees',
 'kolanut',
 'lemon',
 'lentil',
 'lettuce', 
 'linseed',
 'lime',
 'macadamia',
 'maize',
 'maize _cassava',
 'malambe trees',
 'mandarin',
 'mango',
 'masau tree',
 'melon',
 'mexican apple',
 'millet',
 'mint',
 'mix (masuku, avocado)',
 'mix (tea and pineapple)',
 'mkhuthe tree',
 'moringa',
 'mulberry',
 'mung bean/ masho',
 'mustard',
 'oil bean',
 'oil palm',
 'okra',
 'onion',
 'orange',
 'other',
 'papaya',
 'paprika',
 'parsley',
 'passion fruit',
 'pea',
 'peach',  
 'pear',
 'pepper',
 'pigeon pea',
 'pine',
 'pineapple',
 'potato',
 'pumpkin',
 'pumpkin leave',
 'pumpkin seed',
 'rape seed',
 'red kidney bean',
 'red pepper',
 'red sorrel',
 'rice',
 'rocket',
 'rubber',
 'rue',
 'sacred basil',
 'savory',
 'sesame',
 'sorghum',
 'sorrel',
 'soybean',
 'spinach',
 'strawberry',
 'sugarcane',
 'sunflower',
 'sweet pea',
 'sweet potato',
 'taro',
 'tea',
 'teff',
 'tiger nut',
 'tobacco',
 'tomato',
 'topetope',
 'tumeric',
 'vanilla',
 'vetch',
 'walnut',
 'watermelon',
 'water yam',
 'wheat',
 'white cumin',
 'woody tree',
 'yam',
 'zucchini',
 ###
 'apricot',
 'grapefruit',
 'haricot bean',
 'mix (acacia, mango, malaina, mpoza)',
 'mix (cassava, maize)',
 'mix (coffee, avocado, blue gum, banana, peache, papaya, tangerine)',
 'mix (coffee, banana)',
 'mix (mango ,blue gum, guava)',
 'mix (mango, avocado)',
 'mix (mango, banana)',
 'mix (mango, guava)',
 'mix (mango, naphini)',
 'mix (mango, pakhomo)',
 'mung bean',
 'nyowe tree',
 'oat',
 'other (cash crop)',
 'other (oil seed)',
 'plum', 
]

# dictionary for crop name harmonisation
crop_harmonisation_dct = {
    "other land": np.nan,
    "grazing land": np.nan,
    "temporary gr": np.nan,
    "bananas": "banana",
    "acha": "fonio",
    "agbono(oro seed)": "agbono (oro seed)",
    "apples": "apple",
    "avacoda": "avocado",
    "avacodo": "avocado",
    "avocado pear": "avocado",
    "avocados": "avocado",
    "bambara groundnut": "bambara bean",
    "bambara nut": "bambara bean",
    "banana food": "banana",
    "banana sweet": "banana",
    "bananas": "banana",
    "barely": "barley",
    "beans": "bean",
    "beeni-seed/sesame": "sesame",
    "beer root": "beet",
    "calebash": "calabash",
    "carrots": "carrot",
    "blue gum (eucalyptus globus)": "blue gum",
    "cashew": "cashew nut",
    "cassava old": "cassava",
    "castor beans": "castor bean",
    "chick peas": "chickpea",
    "chilies": "chilli pepper",
    "chilli": "chilli pepper",
    "chinangwa": "cassava",
    "chinangwa cha ku mtunda": "cassava",
    "chinangwa cha pakhomo": "cassava",
    "cocoa pod": "cocoa",
    "coco yam": "cocoyam",
    "coffee (arabica)": "coffee",
    "coffee (robusta)": "coffee",
    "coffee all": "coffee",
    "corn": "maize",
    "cow pea": "cowpea",
    "cow peas": "cowpea",
    "dodo": "plantain",
    "eggplants": "eggplant",
    "field peas": "field pea",
    "glisidia": "gliricidia",
    "glylicidia": "gliricidia",
    "godere": "taro",
    "granadillas": "granadilla",
    "green beans": "green bean",
    "ground nut/peanuts": "groundnut",
    "ground nuts": "groundnut",
    "groundnuts": "groundnut",
    "guinea corn (sorghum)": "sorghum",
    "guinea courn/sorghum": "sorghum",
    "haricot beans": "haricot bean",
    "horse beans": "horse bean",
    "irish potatoes": "potato",
    "jakaranda": "jacaranda",
    "jaxatu eggplant": "eggplant",
    "kachere": "kachere tree",
    "kadale": "kadale tree",
    "kolanut unshelled": "kolanut",
    "lemons": "lemon",
    "lentils": "lentil",
    "letus": "lettuce",
    "lineseed": "linseed",
    "majambula": "jambula",
    "malalanje": "orange",
    "malambe": "malambe tree",
    "kadale trees": "kadale tree",
    "kalama trees": "kalama tree",
    "kantchidwi trees": "kantchidwi tree",
    'leeks': 'leek',
    "malambe trees": "malambe tree",
    "mandarins": "mandarin",
    "tangerine": "mandarin",
    "mandarin/tangerine": "mandarin",
    "mango ,bluegum and guava": "mango, bluegum and guava",
    "mangos": "mango",
    "mango a pakhomo": "mango",
    "mango and naphini": "mango and amaranth",
    "mango angono": "mango",
    "mango mango a ku munda wakumtunda": "mango",
    "mango pakhomo": "mango",
    "manthunya (wild fruits)": "wild fruits",
    "manyokkola": "cassava",
    "manyokola": "cassava",
    "mapapaya": "papaya",
    "mapeyala": "avocado",
    "masau": "masau tree",
    "masau trees": "masau tree",
    "masaue": "masau tree",
    "masawu": "masau tree",
    "masua": "masau tree",
    "masungazungu cassava for tg02": "cassava",
    "melon/egusi": "melon",
    "millet/maiwa": "millet",
    "mkhuthe trees": "mkhuthe tree",
    "mlambe": "baobab",
    "molinga": "moringa",
    "mpundu trees": "mpundu tree",
    "msewa trees": "msewa tree",
    "mpapa": "papaya",
    "msangu": "msangu tree",
    "mtengo wa msangu": "msangu tree",
    "mulambe": "baobab",
    "mthethe": "faidherbia albida",
    "muimbi trees": "muimbi tree",
    "musekese": "musekese tree",
    "musekese trees": "musekese tree",
    "mwimbi": "finger millet",
    "nanazi": "pineapple",
    "naphini": "amaranth",
    "napini": "amaranth",
    "nsewa trees": "nsewa tree",
    "nthethe": "faidherbia albida",
    "nthochi": "banana",
    "nzimbe": "cassava",
    "oats": "oat",
    "oil palm tree": "oil palm",
    "okro": "okra",
    "onions": "onion",
    "oranges": "orange",
    "other root c": "other (root crop)",
    "other(specify)": "other",
    "others": "other",
    "other cereal": "other (cereal)",
    "other oil seed": "other (oil seed)",
    "other pulses": "other (pulse)",
    "other spices": "other (spice)",
    "other vegetable": "other (vegetable)",
    "palm kernel": "oil palm",
    "palm oil": "oil palm",
    "pawpaw": "papaya",
    "peanut": "groundnut",
    "pepper, chilli (shombo)": "pepper",
    "pepper, small (rodo)": "pepper",
    "pepper, sweet/bell (tatashe)": "bell pepper",
    "peyala": "avocado",
    "pigeon peas": "pigeon pea",
    "pigeonpea": "pigeon pea",
    "pinapples": "pinapple",
    "pineapples": "pineapple",
    "irish potato": "potato",
    "potato, irish": "potato",
    "potatoes": "potato",
    "poza (custard apple)": "custard apple",
    "pumpkin fruit": "pumpkin",
    "pumpkin leaves": "pumpkin leave",
    "pumpkins": "pumpkin",
    "red kideny beans": "red kidney bean",
    "shelled ground nuts": "groundnut",
    "shelled maize(grain)": "maize",
    "shiferaw": "moringa",
    "simsim": "sesame",
    "small pepper": "pepper",
    "sweet pepper": "bell pepper",
    "soya beans": "soybean",
    "sugar cane": "sugarcane",
    "sun flower": "sunflower",
    "sweet potatoes": "sweet potato",
    "three leave yam": "yam",
    "tobbaco": "tobacco",
    "tomatoes": "tomato",
    "unshelled ground nuts": "groundnut",
    "unshelled maize(cob)": "maize",
    "unshelled melon": "melon",
    "unshelled rice(paddy)": "rice",
    "water melon": "watermelon",
    "white lumin": "white lupin",
    "white yam": "yam",
    "yam, three leaved": "yam",
    "yam, white": "yam",
    "yam, yellow": "yam",
    "yellow yam": "yam",
    "zobo": "sorrel",
###
    "apples (mexican)": "apple",
    "banana (beer)": "banana",
    "banana (food)": "banana",
    "banana (sweet)": "banana",
    "cassava (mkondezi) for tg02": "cassava",
    "cassava (old)": "cassava",
    "chick pea": "chickpea",
    "cocoa (pod)": "cocoa",
    "cotton (seed)": "cotton",
    "cowpea (fodder)": "cowpea",
    "eggplant (jaxatu)": "eggplant",
    "fodder": np.nan,
    "groundnut (peanut)": "groundnut",
    "groundnut (shelled)": "groundnut",
    "groundnut (unshelled)": "groundnut",
    "kolanut (unshelled)": "kolanut",
    "maize (shelled/ grain)": "maize",
    "maize (unshelled/ cob)": "maize",
    "mandarin (tangerine)": "mandarin",
    "mango (angono)": "mango",
    "mango (mango a ku munda wakumtunda)": "mango",
    "melon (egusi)": "melon",
    "melon (unshelled)": "melon",
    "millet (maiwa)": "millet",
    "mulberries": "mulberry",
    "mung bean (masho)": "mung bean",
    "other (land)": np.nan,
    "other (cereals)": "other (cereal)",
    "other (fruits)": "other (fruit)",
    "other (pulses)": "other (pulse)",
    "other (root c)": "other (root crop)",
    "other (spices)": "other (spice)",
    "other (vegetables)": "other (vegetable)",
    "paddy (unshelled rice)": "rice",
    "papaya (pawpaw)": "papaya",
    'pepper (bell)': "bell pepper",
    'pepper (black)': "black pepper",
    'pepper (chilli)': "chilli pepper",
    'pepper (chilli/ shombo)': "chilli pepper",
    'pepper (green)': "green pepper",
    'pepper (red)': "red pepper",
    'pepper (small)': "pepper",
    'pepper (sweet)': "bell pepper",
    'pepper (sweet/ bell/ tatashe)': "bell pepper",
    "potato (irish)": "potato",
    "poza (custard apples)": "custard apple",
    "pumpkin (fruit)": "pumpkin",
    "pumpkin (leave)": "pumpkin leave",
    "pumpkin (seed)": "pumpkin seed",
    "sesame (beeni-seed)": "sesame",
    "sisol": "sisal",
    "sorghum (guinea corn)": "sorghum",
    "tea and pineapples": "tea and pineapple",
    "yam (three leaved)": "yam",
    "yam (water)": "water yam",
    "yam (white)": "yam",
    "yam (yellow)": "yam",
    "baw baw fruit": "papaya",
    "lichesi": "lychee",
    "mandimu": "lemon",
    "maples": "apple",
    "masuku": "loquat",
    "matsuku": "loquat",
    "maula": "plum",
    "mbembwa": "guava",
    "mkhuthe": "moringa",
    "mnyowe": "mushroom",
    "mpoza": "custard apple",
    "mapoza": "custard apple",
    "nanches": "loquat",
    "nimu": "neem",
    "thochi": "banana",
}

# generate new column: simplified cropname
keep_lst = set(crop_target_lst) | set(crop_harmonisation_dct.values())
keep_lst = [x for x in keep_lst if pd.notna(x)]

# map original crop names to simplified names
mapped = lsms_pd["crop"].map(crop_harmonisation_dct).fillna(lsms_pd["crop"])

# assign simplified crop names to new column, set to "other" if not in keep_lst
lsms_pd["crop_simplified"] = mapped.where(mapped.isin(keep_lst), "other")


# as by current manuscript: re-order column names & drop column "season"
col_order_lst = [
 'hhID',
 'fieldID',
 'plotID',
 'crop',
 'crop_simplified',    
 'crop_area_share',
 'planting_month',
 'planting_year',
 'harvest_month_begin',
 'harvest_year_begin',
 'harvest_month_end',
 'harvest_year_end',
 'country',
 'adm1',
 'adm2',
 'adm3',
 'adm4',
 'lat',
 'lon',
 'GPS_level',
 'plot_area_reported_localUnit',
 'localUnit_area',
 'plot_area_measured_ha',
 'plot_area_reported_ha',
#  'season',
 'dataset_name',
 'dataset_doi',
]

# re-order columns
lsms_pd = lsms_pd[col_order_lst]

# store updated dataset to disk
lsms_pd.to_csv("../AfricanCropCalendar_cleanCropname.csv", index=False)




### descriptive stats
##########################################################

# list all cropnames in dataset: end
crop_obs_end_lst = sorted(lsms_pd["crop_simplified"].dropna().unique().tolist())

print('Number of unprocessed crop names:', len(crop_obs_start_lst) )
print('Number of harmonised crop names:', len(crop_obs_end_lst) )



